export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const SERAH_GAMES_SUCCESS = 'SERAH_GAMES_SUCCESS';

export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS';
export const LOAD_MENUS_SUCCESS = 'LOAD_MENUS_SUCCESS';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';

export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';

export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
